export const APP_NAME = "Kadô-kou";
export const SITE_URL = "https://kadokou.gastsar.fr";
export const SITE_DESCRIPTION =
  "Kadô-kou (Kadokou, Kado-kou) est l'app gratuite de wishlist. Créez votre liste de mariage ou d'anniversaire, partagez vos idées cadeaux et organisez vos événements simplement.";

export const SEO = {
  defaultTitle: `Kadô-kou (Kadokou) — Application Wishlist & Liste de Cadeaux Gratuite`,
  defaultDescription:
    "Kadô-kou (aussi appelé Kadokou, Kado-kou) est l'application gratuite de wishlist et liste de cadeaux. Créez votre liste de mariage, de naissance ou d'anniversaire, partagez vos idées cadeaux avec vos proches et organisez vos réceptions en toute simplicité.",
  defaultImage: "/android-chrome-512x512.png",
  twitterHandle: "@kadokou",
  separator: "|",
  keywords: [
    // ═══ Nom de l'app — Toutes les variantes orthographiques ═══
    "kadokou",
    "kado kou",
    "kadôkou",
    "kadô-kou",
    "kado-kou",
    "kadô kou",
    "kadokou app",
    "kadokou application",
    "kado-kou application",
    "kadokou liste de cadeaux",
    "kado-kou wishlist",
    "kadokou wishlist",
    "application kadokou",
    "application kado-kou",
    "telecharger kadokou",
    "télécharger kadokou",
    "télécharger kado-kou",
    "kadokou gratuit",
    "kado-kou gratuit",
    "kadokou avis",
    "kadokou android",
    // ═══ Recherches application / wishlist ═══
    "application wishlist",
    "application liste de cadeaux",
    "application de cadeaux",
    "app wishlist",
    "app liste de cadeaux",
    "meilleure application wishlist",
    "meilleure application liste de cadeaux",
    "meilleure app cadeaux",
    "application gratuite wishlist",
    "application gratuite liste de cadeaux",
    "wishlist application gratuite",
    "wishlist app",
    "wishlist en ligne",
    "wishlist en ligne gratuite",
    "créer une wishlist",
    "créer sa wishlist",
    "ma wishlist",
    "wishlist cadeau",
    "wishlist",
    // ═══ Liste de cadeaux ═══
    "liste de cadeaux",
    "liste de cadeaux en ligne",
    "créer une liste de cadeaux",
    "créer ma liste de cadeaux",
    "faire une liste de cadeaux",
    "liste de cadeaux gratuite",
    "collection de cadeaux",
    "registre de cadeaux",
    "partager sa liste de cadeaux",
    "gestion cadeaux",
    "cadeau en ligne",
    "liste de souhaits",
    "liste de souhaits en ligne",
    "liste d'envies",
    // ═══ Événements spécifiques ═══
    "liste de mariage",
    "liste de mariage en ligne",
    "liste de mariage gratuite",
    "cadeau de mariage",
    "liste de naissance",
    "liste de naissance en ligne",
    "liste de naissance gratuite",
    "cadeau de naissance",
    "cadeau anniversaire",
    "liste d'anniversaire",
    "idées de cadeaux d'anniversaire",
    "baby shower liste",
    "cagnotte en ligne",
    "organiser un événement",
    "organiser une réception",
    "liste cadeau noël",
    "liste de noël en ligne",
    // ═══ Idées cadeaux ═══
    "idée cadeau",
    "idées cadeaux",
    "trouver une idée cadeau",
    "idée cadeau original",
    "idée cadeau femme",
    "idée cadeau homme",
    "quel cadeau offrir",
    // ═══ Éditeur / Créateur ═══
    "devengalere",
    "dev en galere",
    "yves narson kevine",
  ],
};

// Informations légales à compléter par l'utilisateur
export const LEGAL_INFO = {
  companyName: "Devengalere — Dev en galère",
  legalForm: "Entrepreneur Individuel",
  capital: "0 €",
  address: "TOULOUSE, 31500",
  siret: "94060059600024",
  rcs: "TOULOUSE",
  tva: "FR00000000000",
  email: "yvesnarsonkevine@gmail.com",
  publicationDirector: "Yves Narson Kevine",
  host: {
    name: "Ionos.",
    address: "7, place de la Gare FR 57200 Sarreguemines",
    url: "https://www.ionos.fr",
    tel: "",
  },
};
